export enum UserRole {
  VENDOR = 'VENDOR',
  CUSTOMER = 'CUSTOMER',
  NORMAL_USER = 'NORMAL_USER',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN'
}

export enum OrderStatus {
  WAITING_FOR_DRIVER = 'WAITING_FOR_DRIVER', // PRD: Submitted state
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  PICKED_UP = 'PICKED_UP',
  ON_THE_WAY = 'ON_THE_WAY',
  NEAR_DESTINATION = 'NEAR_DESTINATION',
  DELIVERED = 'DELIVERED',
  COD_COLLECTED = 'COD_COLLECTED', // PRD: For COD specific completions
  CANCELLED = 'CANCELLED'
}

export enum PackageType {
  STANDARD = 'STANDARD',
  DOCUMENT = 'DOCUMENT',
  PERISHABLE = 'PERISHABLE',
  FRAGILE = 'FRAGILE',
  PHARMACY = 'PHARMACY'
}